# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-QTappsmarthome"
BBFILE_PATTERN_meta-QTappsmarthome = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-QTappsmarthome = "6"

LAYERDEPENDS_meta-QTappsmarthome = "core"
LAYERSERIES_COMPAT_meta-QTappsmarthome = "dunfell"
